import = [
  "/home/koral/.nvm/versions/node/v20.17.0/lib/node_modules/alacritty-themes/themes/Afterglow.toml"
]

[font]
size = 12

  [font.normal]
  family = "Iosevka Nerd Font"
  style = "Regular"

  [font.bold]
  family = "Iosevka Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Iosevka Nerd Font"
  style = "Italic"
